[package]
name = "deterministic_rustdoc_types"
version = "0.1.0"
edition = "2024"

[dependencies]
# CLI argument parsing
pico-args = "0.5.0"

# `rustdoc` JSON deserialization and queries
serde_json = "1.0.140"
jsonpath-rust = "1.0.2"

# Error propagation and contexts
anyhow = "1.0.98"
